var fixtures = {
    "asda": {
        "message": "SUCCESS: Result available",
        "status": "done",
        "status_code": 3,
        "result": {
            "establishment": "ASDA",
            "validatedEstablishment": true,
            "date": "2020-01-02 17:49:35",
            "total": "18.880",
            "url": "www.asda.com",
            "phoneNumber": "01983 640246",
            "paymentMethod": "Mastercard",
            "address": "Newport Isle of Wight, St Georges Way, Newport, PO30 2QH",
            "cash": "0.000",
            "change": "0.000",
            "validatedTotal": false,
            "subTotal": "0.000",
            "validatedSubTotal": false,
            "tax": "0.000",
            "tip": "0.000",
            "taxes": [],
            "serviceCharges": [],
            "discount": "0.000",
            "rounding": "0.000",
            "discounts": [],
            "lineItems": [{
                "qty": 0,
                "desc": "SP BUTTER 000002040596K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "St Georges Way,Newport,PO302QH SP BUTTER K",
                "lineTotal": "1.450",
                "productCode": "000002040596",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "SP BUTTER 000002040596K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "SP BUTTER K",
                "lineTotal": "1.450",
                "productCode": "000002040596",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "POT NOODLE 500011820372K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "POT NOODLE K",
                "lineTotal": "2.000",
                "productCode": "500011820372",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "SUPERNOODLES 500035440510K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "SUPERNOODLES K",
                "lineTotal": "0.500",
                "productCode": "500035440510",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "GREEN BEANS 505478151285K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "GREEN BEANS K",
                "lineTotal": "0.750",
                "productCode": "505478151285",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "CHICKEN 505407026610K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "CHICKEN K",
                "lineTotal": "5.190",
                "productCode": "505407026610",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "NAKED NOODLE 505066502374K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "NAKED NOODLE K",
                "lineTotal": "0.750",
                "productCode": "505066502374",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "PEPERAMI 425109740714K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "PEPERAMI K",
                "lineTotal": "1.350",
                "productCode": "425109740714",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "RICE POT 505066503888K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "RICE POT K",
                "lineTotal": "0.750",
                "productCode": "505066503888",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "LAUNDRY 800184106691K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "V"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "LAUNDRY K",
                "lineTotal": "3.000",
                "productCode": "800184106691",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "ROLLS 020322000069K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "ROLLS K",
                "lineTotal": "0.690",
                "productCode": "020322000069",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "SUPERNOODLES 500035440509K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "SUPERNOODLES K",
                "lineTotal": "0.500",
                "productCode": "500035440509",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "SUPERNOODLES 500035440509K",
                "unit": "",
                "price": "0.000",
                "symbols": ["£", "D"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "SUPERNOODLES K",
                "lineTotal": "0.500",
                "productCode": "500035440509",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "LOTTO 505478132875",
                "unit": "",
                "price": "0.000",
                "symbols": ["£"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "LOTTO",
                "lineTotal": "2.000",
                "productCode": "505478132875",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "MNFCTRS COUPON",
                "unit": "",
                "price": "0.000",
                "symbols": ["-", "£"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "MNFCTRS COUPON",
                "lineTotal": "-2.000",
                "productCode": "",
                "customFields": {}
            }],
            "summaryItems": [{
                "qty": 0,
                "desc": "TOTAL",
                "unit": "",
                "price": "0.000",
                "symbols": ["£"],
                "discount": "0.000",
                "lineType": "Total",
                "descClean": "TOTAL",
                "lineTotal": "18.880",
                "productCode": "",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "TOTAL EPS",
                "unit": "",
                "price": "0.000",
                "symbols": ["£"],
                "discount": "0.000",
                "lineType": "Total",
                "descClean": "TOTAL EPS",
                "lineTotal": "18.880",
                "productCode": "",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "CARD",
                "unit": "",
                "price": "0.000",
                "symbols": ["£"],
                "discount": "0.000",
                "lineType": "Total",
                "descClean": "CARD",
                "lineTotal": "18.880",
                "productCode": "",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "TOTAL EPS",
                "unit": "",
                "price": "0.000",
                "symbols": ["£"],
                "discount": "0.000",
                "lineType": "Total",
                "descClean": "TOTAL EPS",
                "lineTotal": "18.880",
                "productCode": "",
                "customFields": {}
            }],
            "subTotalConfidence": 0,
            "taxesConfidence": [],
            "serviceChargeConfidences": [],
            "discountConfidences": [],
            "totalConfidence": 0.99,
            "dateConfidence": 0.95,
            "establishmentConfidence": 0.99,
            "tipConfidence": 0,
            "cashConfidence": 0,
            "changeConfidence": 0,
            "roundingConfidence": 0,
            "customFields": {
                "URL": "WWW.ASDA.COM",
                "Country": "GBR",
                "StoreID": "",
                "Currency": "GBP",
                "VATNumber": "",
                "ExpenseType": "",
                "PaymentMethod": "Mastercard",
                "CardLast4Digits": ""
            },
            "documentType": "receipt",
            "currency": "GBP",
            "barcodes": [],
            "dateISO": "2020-01-02T17:49:35",
            "addressNorm": {
                "city": "Newport",
                "state": "",
                "number": "",
                "street": "St Georges Way",
                "suburb": "",
                "country": "",
                "building": "",
                "postcode": "PO30 2QH"
            },
            "expenseType": "None",
            "otherData": []
        },
        "success": true,
        "code": 202
    },

    "waitrose": {
        "message": "SUCCESS: Result available",
        "status": "done",
        "status_code": 3,
        "result": {
            "establishment": "Waitrose",
            "validatedEstablishment": false,
            "date": "2020-03-02 20:03:40",
            "total": "1.080",
            "url": "www.waitrose.com/eastcowes",
            "phoneNumber": "313 505 4200",
            "paymentMethod": "Mastercard",
            "address": "East Cowes 313: 01983 282413",
            "cash": "0.000",
            "change": "0.000",
            "validatedTotal": false,
            "subTotal": "1.080",
            "validatedSubTotal": true,
            "tax": "0.000",
            "tip": "0.000",
            "taxes": [],
            "serviceCharges": [],
            "discount": "0.000",
            "rounding": "0.000",
            "discounts": [],
            "lineItems": [{
                "qty": 0,
                "desc": "SHAWARMA MUSH",
                "unit": "",
                "price": "0.000",
                "symbols": [],
                "discount": "0.000",
                "lineType": "",
                "descClean": "SHAWARMA MUSH Reduced item",
                "lineTotal": "0.250",
                "productCode": "",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "WR SHAWARMA MUSH WRA",
                "unit": "",
                "price": "0.000",
                "symbols": [],
                "discount": "0.000",
                "lineType": "",
                "descClean": "WR SHAWARMA MUSH WRA Reduced item",
                "lineTotal": "0.250",
                "productCode": "",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "TAIKO KATSU BENTO",
                "unit": "",
                "price": "0.000",
                "symbols": [],
                "discount": "0.000",
                "lineType": "",
                "descClean": "TAIKO KATSU BENTO Reduced item",
                "lineTotal": "0.490",
                "productCode": "",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "REALLY GRLCKY GARLIC",
                "unit": "",
                "price": "0.000",
                "symbols": [],
                "discount": "0.000",
                "lineType": "",
                "descClean": "REALLY GRLCKY GARLIC Partner Discount",
                "lineTotal": "0.290",
                "productCode": "",
                "customFields": {}
            }, {
                "qty": 4,
                "desc": "WR £1.28 @ 15.0%",
                "unit": "",
                "price": "0.000",
                "symbols": ["-"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "WR £1.28 @ 15.0 items",
                "lineTotal": "-0.200",
                "productCode": "",
                "customFields": {}
            }],
            "summaryItems": [{
                "qty": 0,
                "desc": "BALANCE QUE",
                "unit": "",
                "price": "0.000",
                "symbols": ["£"],
                "discount": "0.000",
                "lineType": "SubTotal",
                "descClean": "BALANCE QUE",
                "lineTotal": "1.080",
                "productCode": "",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "0645",
                "unit": "",
                "price": "0.000",
                "symbols": ["£"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "0645",
                "lineTotal": "1.080",
                "productCode": "",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "CHANGE",
                "unit": "",
                "price": "0.000",
                "symbols": [],
                "discount": "0.000",
                "lineType": "",
                "descClean": "CHANGE",
                "lineTotal": "0.000",
                "productCode": "",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "TOTAL",
                "unit": "",
                "price": "0.000",
                "symbols": ["G", "B", "P"],
                "discount": "0.000",
                "lineType": "Total",
                "descClean": "TOTAL",
                "lineTotal": "1.080",
                "productCode": "",
                "customFields": {}
            }],
            "subTotalConfidence": 0.99,
            "taxesConfidence": [],
            "serviceChargeConfidences": [],
            "discountConfidences": [],
            "totalConfidence": 0.7,
            "dateConfidence": 0.7,
            "establishmentConfidence": 0.99,
            "tipConfidence": 0,
            "cashConfidence": 0,
            "changeConfidence": 0,
            "roundingConfidence": 0,
            "customFields": {
                "URL": "www.waitrose.com/eastcowes",
                "Country": "GBR",
                "StoreID": "",
                "Currency": "GBP",
                "VATNumber": "",
                "ExpenseType": "",
                "PaymentMethod": "Mastercard",
                "CardLast4Digits": "0645"
            },
            "documentType": "receipt",
            "currency": "GBP",
            "barcodes": [],
            "dateISO": "2020-03-02T20:03:40",
            "addressNorm": {
                "city": "East Cowes",
                "state": "",
                "number": "01983",
                "street": "282413",
                "suburb": "",
                "country": "",
                "building": "",
                "postcode": ""
            },
            "expenseType": "None",
            "otherData": []
        },
        "success": true,
        "code": 202
    },
    "dessert": {

        "message": "SUCCESS: Result available",
        "status": "done",
        "status_code": 3,
        "result": {
            "establishment": "Little",
            "validatedEstablishment": false,
            "date": "2020-02-01 12:20:00",
            "total": "10.550",
            "url": "",
            "phoneNumber": "",
            "paymentMethod": "",
            "address": "9 Pier Street, Sandown, Isle of Wight P036",
            "cash": "0.000",
            "change": "0.000",
            "validatedTotal": false,
            "subTotal": "0.000",
            "validatedSubTotal": false,
            "tax": "0.000",
            "tip": "0.000",
            "taxes": [],
            "serviceCharges": [],
            "discount": "0.000",
            "rounding": "0.000",
            "discounts": [],
            "lineItems": [{
                "qty": 9,
                "desc": "9 Pier Street,Sandown,Isle of Wight",
                "unit": "",
                "price": "0.000",
                "symbols": ["P"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "Pier Street,Sandown,Isle of Wight 8JR",
                "lineTotal": "36.000",
                "productCode": "",
                "customFields": {},
                "supplementaryLineItems": {
                    "above": [],
                    "below": [{
                        "qty": 0,
                        "desc": "Opening Soon",
                        "unit": "",
                        "price": "0.000",
                        "symbols": [],
                        "discount": "0.000",
                        "lineType": "",
                        "descClean": "Opening Soon",
                        "lineTotal": "0.000",
                        "confidence": "0.500",
                        "productCode": "",
                        "customFields": {}
                    }, {
                        "qty": 20,
                        "desc": "Sat 1st Feb 20 12 : 20 PM Server",
                        "unit": "",
                        "price": "0.000",
                        "symbols": [],
                        "discount": "0.000",
                        "lineType": "",
                        "descClean": "Sat 1 Feb 12 : 20 PM Server",
                        "lineTotal": "0.000",
                        "confidence": "0.500",
                        "productCode": "",
                        "customFields": {}
                    }, {
                        "qty": 0,
                        "desc": "Carley Sale No : 28507",
                        "unit": "",
                        "price": "0.000",
                        "symbols": [],
                        "discount": "0.000",
                        "lineType": "",
                        "descClean": "Carley Sale No : 28507",
                        "lineTotal": "0.000",
                        "confidence": "0.500",
                        "productCode": "",
                        "customFields": {}
                    }]
                }
            }, {
                "qty": 1,
                "desc": "5.95",
                "unit": "",
                "price": "5.950",
                "symbols": [],
                "discount": "0.000",
                "lineType": "",
                "descClean": "Croissant",
                "lineTotal": "5.950",
                "productCode": "",
                "customFields": {},
                "supplementaryLineItems": {
                    "above": [{
                        "qty": 0,
                        "desc": "# Description Price Subtotal",
                        "unit": "",
                        "price": "0.000",
                        "symbols": [],
                        "discount": "0.000",
                        "lineType": "",
                        "descClean": "# Description Price Subtotal",
                        "lineTotal": "0.000",
                        "confidence": "0.500",
                        "productCode": "",
                        "customFields": {}
                    }, {
                        "qty": 0,
                        "desc": "Croissants / Sweet",
                        "unit": "",
                        "price": "0.000",
                        "symbols": [],
                        "discount": "0.000",
                        "lineType": "",
                        "descClean": "Croissants Sweet",
                        "lineTotal": "0.000",
                        "confidence": "0.500",
                        "productCode": "",
                        "customFields": {}
                    }, {
                        "qty": 0,
                        "desc": "It ' s All Mine",
                        "unit": "",
                        "price": "0.000",
                        "symbols": [],
                        "discount": "0.000",
                        "lineType": "",
                        "descClean": "It ' s All Mine",
                        "lineTotal": "0.000",
                        "confidence": "0.500",
                        "productCode": "",
                        "customFields": {}
                    }],
                    "below": [{
                        "qty": 0,
                        "desc": "None + 0.00",
                        "unit": "",
                        "price": "0.000",
                        "symbols": [],
                        "discount": "0.000",
                        "lineType": "",
                        "descClean": "None + 0.00",
                        "lineTotal": "0.000",
                        "confidence": "0.500",
                        "productCode": "",
                        "customFields": {}
                    }, {
                        "qty": 0,
                        "desc": "Coffee Blend",
                        "unit": "",
                        "price": "0.000",
                        "symbols": [],
                        "discount": "0.000",
                        "lineType": "",
                        "descClean": "Coffee Blend",
                        "lineTotal": "0.000",
                        "confidence": "0.500",
                        "productCode": "",
                        "customFields": {}
                    }]
                }
            }, {
                "qty": 0,
                "desc": "Cookies & Cream 3.95",
                "unit": "",
                "price": "0.000",
                "symbols": [],
                "discount": "0.000",
                "lineType": "",
                "descClean": "Cookies Cream 3.95 • Whipped Cream + 0.65",
                "lineTotal": "4.600",
                "productCode": "",
                "customFields": {},
                "supplementaryLineItems": {
                    "above": [{
                        "qty": 0,
                        "desc": "None + 0.00",
                        "unit": "",
                        "price": "0.000",
                        "symbols": [],
                        "discount": "0.000",
                        "lineType": "",
                        "descClean": "None + 0.00",
                        "lineTotal": "0.000",
                        "confidence": "0.500",
                        "productCode": "",
                        "customFields": {}
                    }, {
                        "qty": 0,
                        "desc": "Coffee Blend",
                        "unit": "",
                        "price": "0.000",
                        "symbols": [],
                        "discount": "0.000",
                        "lineType": "",
                        "descClean": "Coffee Blend",
                        "lineTotal": "0.000",
                        "confidence": "0.500",
                        "productCode": "",
                        "customFields": {}
                    }],
                    "below": []
                }
            }, {
                "qty": 0,
                "desc": "GRAND",
                "unit": "",
                "price": "0.000",
                "symbols": ["£"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "GRAND",
                "lineTotal": "10.550",
                "productCode": "",
                "customFields": {}
            }, {
                "qty": 0,
                "desc": "",
                "unit": "",
                "price": "0.000",
                "symbols": [")", "£"],
                "discount": "0.000",
                "lineType": "",
                "descClean": "PAID ( evo _ cardmachine ) £10",
                "lineTotal": "10.550",
                "productCode": "",
                "customFields": {}
            }],
            "summaryItems": [],
            "subTotalConfidence": 0,
            "taxesConfidence": [],
            "serviceChargeConfidences": [],
            "discountConfidences": [],
            "totalConfidence": 0.5,
            "dateConfidence": 0.95,
            "establishmentConfidence": 0.8,
            "tipConfidence": 0,
            "cashConfidence": 0,
            "changeConfidence": 0,
            "roundingConfidence": 0,
            "customFields": {
                "URL": "",
                "Country": "GBR",
                "StoreID": "",
                "Currency": "GBP",
                "VATNumber": "",
                "ExpenseType": "Meals/Individual Meals while Traveling",
                "PaymentMethod": "",
                "CardLast4Digits": ""
            },
            "documentType": "receipt",
            "currency": "GBP",
            "barcodes": [],
            "dateISO": "2020-02-01T12:20:00",
            "addressNorm": {
                "city": "Sandown",
                "state": "",
                "number": "9",
                "street": "Pier Street",
                "suburb": "",
                "country": "P036",
                "building": "",
                "postcode": ""
            },
            "expenseType": "Meals/Individual Meals while Traveling",
            "otherData": []
        },
        "success": true,
        "code": 202
    },
    get_token_success: {
        "message": "SUCCESS: Image uploaded successfully",
        "status": "success",
        "status_code": 2,
        "token": "naQM25k8KyJPmgxG",
        "success": true,
        "code": 200,
        "duplicate": true,
        "duplicateToken": "naQM25k8KyJPmgxG"
    },
    get_token_error: {
        "success": false,
        "code": 400,
        "message": "ERROR_CLIENT: API key not found"
    },
    get_token_unsupported_file_extension: {
        "message": "ERROR: Unsupported file extension",
        "status": "failed",
        "status_code": 4,
        "success": false,
        "code": 407
    },
    get_token_result_unavailable: {
        "message": "WARNING: Result not yet available",
        "status": "pending",
        "status_code": 1,
        "success": true,
        "code": 301
    }

}

module.exports = fixtures;